
project_id = "nhvkviofvefwbvditgxo"

[functions]
[functions.update-real-time-prices]
verify_jwt = false

[functions.schedule-realtime-prices]
verify_jwt = false

[functions.scheduled-price-update]
verify_jwt = false

[functions.schedule-auto-price-updates]
verify_jwt = false
